travis:
  secure:
    BINSTAR_TOKEN: eyrmQU97kNsSVf2wltaQ+Vqk764d/CB3gl/lGthN3ypmh7UVSJs1y5GQ90kktVLJXmZgmfDbwvB8ejSYtKgTOaZKHkQakgbWbiJEgaNvOFcGnsvTgY/4sa0kMMsJ32mbN0f56aLbjpeCrDjASVNIae8EQu9m/ABVaU7Jg8zBPQgHhUh0cM/tv4E3etaOtPy5u/y1Z7gUqRrtohozEMYYmIdO5NyyO+7oclXFEauP4/yVJU1ixA+JuAYAzVSeDwBe7TM8GrxSmc6VjQsxTdSmvtqfCesLAr92Sqi8LZtjDkCcjkUl+JIWSDaOgVeUc3jn4XjdZ4SDco0Ik6XYJuCQMuj4XBvp7XtK6W7jOXsXanfnmUkyq1dJxmfe0M/Lw8R6Al/Y+a6sLwWLRt6jl4HBNEDT+WvEeeuvtYef1RKeH/IMJQwzih6z9q9Xy1KpeNhQznwEhx8NTBEPE1AtCOJfgc03m17pRd+bNBXw7MitjsTUgT7ReyigobDbPbvwMXdWBUY4bg3EmCc9uJEPCm8gol6kDEBmpIrKEhRMe+IOBVspP+s1NS2B8k7CMqO4+uvV6CEWFngmDdNUVxlA1ZAGk8GjX5SCenAlBHtQ6zV1KuOIMXPWByTyQ4akJHy7AxHmiEExnTD4khM+T+bpLLR9xR3/FL/oUHz9yzoxiZrpOHM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
